title:            Markdown Edit
tagline:          A Beautiful Markdown Editor For Windows
description:      A full-featured Markdown Editor for Windows with an emphasis on content and keyboard shortcuts
canonical:        http://markdownedit.com/
url:              http://markdownedit.com/

# Owner/author information
owner:
  name:           Mike Ward
  avatar:         avatar.png
  bio:            Programmer and Bourbon Drinker
  email:          mike@mike-ward.net
  twitter:        mikeward_aa
  github:         mike-ward
  instagram:      
  dribbble:       
  disqus:         mikeward_aa
  location:       "Ann Arbor, MI  USA"
  # Plug in your disqus shortname!

tools:
  standards:      "HTML, SCSS, Jekyll"
  software:       "git"

# Links to include in top navigation
# For external links add external: true
links:
  - title: Features
    url: /features
  - title: Blog
    url: /blog
  - title: Bugs
    url: https://github.com/mike-ward/Markdown-Edit/issues/
    external: true
  - title: Github
    url: https://github.com/mike-ward/Markdown-Edit/
    external: true
  - title: About
    url: /about

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Detroit
future:      true
highlighter: pygments
markdown:    kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

sass:
    style: :compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]
