version: 1.0.{build}
configuration: Release
before_build:
- cmd: cd src & nuget restore & cd ..
build:
  verbosity: minimal
after_test:
- cmd: cd src\Wix & build.cmd
- cmd: build_zip.cmd
artifacts:
- path: MarkdownEditSetup.msi
  name: installer
- path: MarkdownEdit.zip
  name: portable
deploy: off
os: Visual Studio 2015
